# variable disponible sur https://github.com/osunyorg/theme/blob/main/hugo.yaml

theme: osuny
_merge: deep
params:
  search:
    active: true
    positions: secondary-menu #config custom pour afficher l'icone search dans le menu secondaire
  seo:
    title:
      separator: "-"

  # DESIGN SYSTEM
  logo:
    header: ''
    footer: ''
  menu:
    primary:
      level_2:
        summary:
          active: false
        title:
          active: true

  # SECTIONS
  organizations:
    index:
      taxonomies: true
    single:
      backlinks: true
  persons:
    index:
      layout: grid # grid | list
      taxonomies: true
    single:
      backlinks: true #activé mais author désactivé en attendant MAJ Osuny pour avoir les auteurs dans les projets
      taxonomies:
        position: content # content | hero | none
  posts:
    default_image: true
    date_format: "02/01/2006"
    index:
      layout: list # grid | list
    taxonomies_to_hide: #config custom pour masquer certaines taxonomies
    - "Niveau de diplôme"
    - "Mention"
  projects:
    default_image: true
    date_format: "2006"
    index:
      layout: list # alternate | grid | large | lists
    taxonomies_to_hide: #config custom pour masquer certaines taxonomies
      - "Studio"

  # BLOCKS
  blocks:
    pages:
      alternate:
        more: false