# variable disponible sur https://github.com/osunyorg/theme/blob/main/hugo.yaml

theme: osuny
_merge: deep
cascade:
  - target:
      path: "{/persons,/persons/**,/persons_categories,/persons_categories/**}"
    build:
      render: never
      list: never
params:
  search:
    active: true
    positions:
      - primary #config custom pour afficher l'icone search dans le menu secondaire
  seo:
    title:
      separator: "-"

  # DESIGN SYSTEM
  logo:
    header: ''
    footer: ''
  menu:
    primary:
      level_2:
        summary:
          active: false
        title:
          active: true
  breadcrumb:
    position: after-hero # hero-start | hero-end | after-hero | after-hero-title | none
  share_links:
    enabled: false
  # SECTIONS
  home:
    head:
      title: site
  organizations:
    index:
      taxonomies:
        display: true
        layout: dropdown # dropdown | inline
        show_name: true
    single:
      backlinks: true
  persons:
    index:
      layout: grid # grid | list
      taxonomies:
        display: true
        layout: dropdown # dropdown | inline
        show_name: true
    single:
      backlinks: true #activé mais author désactivé en attendant MAJ Osuny pour avoir les auteurs dans les projets
      taxonomies:
        position: content # content | hero | none
  posts:
    default_image: false
    date_format: "02/01/2006"
    index:
      layout: list # grid | list
  projects:
    default_image: true
    date_format: "2006"
    index:
      layout: list # alternate | grid | large | lists
      options:
        year: true
  
  # IMAGES
  image_sizes:
    sections:
      projects:
        layouts:
          grid:
            mobile:   350
            tablet:   480
            desktop:  576
          list:
            mobile:   350
            tablet:   350
            desktop:  415
      posts:
        layouts:
          list:
            mobile:   240
            tablet:   320
            desktop:  415
      organizations:
        layouts:
          grid:
            mobile:   300
            tablet:   250
            desktop:  210

  # BLOCKS
  blocks:
    pages:
      alternate:
        more: false
    # posts:
    #   list:
    #     arrows: true